// <auto-generated />
using System;
using HotelReservation.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelReservation.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HotelReservation.Domain.Entities.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.CustomerReservation", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("char(36)");

                    b.HasKey("CustomerId", "ReservationId");

                    b.HasIndex("ReservationId");

                    b.ToTable("CustomerReservations");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.DailyPriceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DateTime")
                        .HasColumnType("date");

                    b.Property<Guid>("HotelRoomId")
                        .HasColumnType("char(36)");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("PricePlanId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("HotelRoomId");

                    b.HasIndex("PricePlanId");

                    b.ToTable("DailyPrices");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.HotelRoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<float>("Area")
                        .HasColumnType("float");

                    b.Property<int>("GuestCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PricePlanId")
                        .HasColumnType("char(36)");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PricePlanId");

                    b.ToTable("HotelRooms");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.HotelRoomReservation", b =>
                {
                    b.Property<Guid>("HotelRoomId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("char(36)");

                    b.HasKey("HotelRoomId", "ReservationId");

                    b.HasIndex("ReservationId");

                    b.ToTable("HotelRoomReservations");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.PricePlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PricePlans");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.ReservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.CustomerReservation", b =>
                {
                    b.HasOne("HotelReservation.Domain.Entities.CustomerEntity", "Customer")
                        .WithMany("CustomerReservation")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelReservation.Domain.Entities.ReservationEntity", "Reservation")
                        .WithMany("CustomerReservations")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.DailyPriceEntity", b =>
                {
                    b.HasOne("HotelReservation.Domain.Entities.HotelRoomEntity", "HotelRoom")
                        .WithMany()
                        .HasForeignKey("HotelRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelReservation.Domain.Entities.PricePlanEntity", "PricePlan")
                        .WithMany("DailyPrices")
                        .HasForeignKey("PricePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HotelRoom");

                    b.Navigation("PricePlan");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.HotelRoomEntity", b =>
                {
                    b.HasOne("HotelReservation.Domain.Entities.PricePlanEntity", "PricePlanEntity")
                        .WithMany("HotelRooms")
                        .HasForeignKey("PricePlanId");

                    b.Navigation("PricePlanEntity");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.HotelRoomReservation", b =>
                {
                    b.HasOne("HotelReservation.Domain.Entities.HotelRoomEntity", "HotelRoom")
                        .WithMany("HotelRoomReservations")
                        .HasForeignKey("HotelRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelReservation.Domain.Entities.ReservationEntity", "Reservation")
                        .WithMany("HotelRoomReservations")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HotelRoom");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.CustomerEntity", b =>
                {
                    b.Navigation("CustomerReservation");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.HotelRoomEntity", b =>
                {
                    b.Navigation("HotelRoomReservations");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.PricePlanEntity", b =>
                {
                    b.Navigation("DailyPrices");

                    b.Navigation("HotelRooms");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.ReservationEntity", b =>
                {
                    b.Navigation("CustomerReservations");

                    b.Navigation("HotelRoomReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
